name: smart_alarm
description: A modern alarm, timer, stopwatch, and world clock app.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  intl: ^0.18.0
  flutter_local_notifications: ^13.0.0
  android_alarm_manager_plus: ^3.0.4
  flutter_native_timezone: ^2.0.0
  permission_handler: ^10.4.0
  flutter_tts: ^3.6.4
  vibration: ^1.7.5
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/
    - assets/images/
